**Task**: Create and manipulate NumPy arrays.

- Create a 1D array of integers from 0 to 9.
- Create a 2D array of shape (3, 3) filled with ones.
- Create a 3x3 identity matrix.
- Create a 1D array of 10 evenly spaced values between 0 and 1.

In [4]:
import numpy as np

zero_to_nine = np.arange(0,10)
three_on_three = np.ones((3,3), dtype=float)
identity_matrix = np.zeros((3,3), dtype=int)
for i in range(identity_matrix.shape[0]):
  identity_matrix[i][i] = 1
identity_matrix_sexy = np.eye(3)
evenly_spaces = np.linspace(0, 1, 10)
evenly_spaces = np.round(evenly_spaces, 2)
print(zero_to_nine)
print(three_on_three)
print(identity_matrix)
print(identity_matrix_sexy)
print(evenly_spaces)

[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


**Task**: Explore array properties and perform basic manipulations.

- Create a 2D array of shape (4, 5) with random integers between 1 and 10.
- Find the shape, size, and data type of the array.
- Reshape the array to shape (5, 4).
- Transpose the reshaped array.

In [14]:
import random as rnd

random_array = np.random.randint(1, 11, size=(4,5))
print(random_array.shape)
print(random_array.size)
print(random_array.dtype)
# print(random_array)
random_array = random_array.reshape((5,4))
print(random_array)
random_array = random_array.transpose()
print(random_array)

(4, 5)
20
int32
[[ 6  5  8  3]
 [ 3  6  8  4]
 [ 6  7  6 10]
 [ 8  3  5  5]
 [ 8  7  2  7]]
[[ 6  3  6  8  8]
 [ 5  6  7  3  7]
 [ 8  8  6  5  2]
 [ 3  4 10  5  7]]


**Task**: Perform element-wise operations and aggregate functions.

- Create two 1D arrays of length 5 with random integers between 1 and 10.
- Perform element-wise addition, subtraction, multiplication, and division.
- Calculate the dot product of the two arrays.
- Find the sum, mean, and standard deviation of the first array.

In [23]:
first_array = np.random.randint(10, size=5)
second_array = np.random.randint(10, size=5)
print("First array: ", first_array)
print("Second array: ", second_array)
print("Element-wise Addition: ", np.add(first_array, second_array))
print("Element-wise Subtraction: ", np.subtract(first_array, second_array))
print("Element-wise Multiplication: ", np.multiply(first_array, second_array))
print("Element-wise Division: ", np.divide(first_array, second_array, where=second_array != 0))
print("Dot Product", np.dot(first_array, second_array))
print("Sum ", np.sum(first_array))
print("Mean ", np.mean(first_array))
print("Std ", np.std(first_array))

First array:  [1 8 7 4 6]
Second array:  [7 4 4 2 7]
Element-wise Addition:  [ 8 12 11  6 13]
Element-wise Subtraction:  [-6  4  3  2 -1]
Element-wise Multiplication:  [ 7 32 28  8 42]
Element-wise Division:  [0.14285714 2.         1.75       2.         0.85714286]
Dot Product 117
Sum  26
Mean  5.2
Std  2.4819347291981715


**Task**: Perform linear algebra operations on matrices.

- Create a 2x2 matrix with random integers between 1 and 5.
- Calculate the inverse of the matrix.
- Compute the determinant of the matrix.
- Find the eigenvalues and eigenvectors of the matrix.

In [ ]:
matrix = np.random.randint(1, 6, size=(2, 2))
print("Matrix:\n", matrix)

# Calculate the inverse of the matrix
try:
    matrix_inverse = np.linalg.inv(matrix)
    print("Inverse of the matrix:\n", matrix_inverse)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

# Compute the determinant of the matrix
matrix_determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", matrix_determinant)

# Find the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)

**Task**: Practice indexing, slicing, and broadcasting.

- Create a 1D array of integers from 0 to 19.
- Extract the subarray containing elements from index 5 to 10.
- Use boolean indexing to select elements greater than 10.
- Create a 2D array of shape (3, 3) and add a 1D array of length 3 to each row using broadcasting.

In [36]:
integers_array = np.arange(0, 19, 1)
subarray = integers_array[5:10]
print(subarray)
greater_than_10 = integers_array[integers_array > 10]
print(greater_than_10) 
three_on_three = np.random.randint(20, size=(3,3))
print(three_on_three)
three_on_three_2 = np.random.randint(20, size=(3,3))
print(three_on_three_2)
print(np.broadcast_arrays(three_on_three, three_on_three_2))

[5 6 7 8 9]
[11 12 13 14 15 16 17 18]
[[15 17 12]
 [ 5  5  7]
 [16  5 16]]
[[10  7  7]
 [13 12 16]
 [14 10  0]]
[[25 24 19]
 [18 17 23]
 [30 15 16]]


**Task**: Generate random numbers and perform operations.

- Generate a 1D array of 5 random numbers from a uniform distribution between 0 and 1.
- Generate a 2D array of shape (3, 3) with random numbers from a standard normal distribution.
- Generate a 1D array of 5 random integers between 10 and 20.

In [ ]:
import numpy as np

# Generate a 1D array of 5 random numbers from a uniform distribution between 0 and 1
uniform_random_numbers = np.random.rand(5)
print("Uniform random numbers:", uniform_random_numbers)

# Generate a 2D array of shape (3, 3) with random numbers from a standard normal distribution
normal_random_numbers = np.random.randn(3, 3)
print("Standard normal random numbers:\n", normal_random_numbers)

# Generate a 1D array of 5 random integers between 10 and 20
random_integers = np.random.randint(10, 21, size=5)
print("Random integers between 10 and 20:", random_integers)

Some PCA play-around

In [ ]:
python

import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Sample data
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0],
              [2.3, 2.7],
              [2, 1.6],
              [1, 1.1],
              [1.5, 1.6],
              [1.1, 0.9]])

# Apply PCA
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X)

# Plot original data and PCA result
plt.scatter(X[:, 0], X[:, 1], label='Original Data')
plt.scatter(X_pca, np.zeros_like(X_pca), label='PCA Result', color='red')
plt.xlabel('X1')
plt.ylabel('X2')
plt.title('PCA Example')
plt.legend()
plt.show()